---
title: "cetable"
output:
   html_document:
      self_contained: false
      keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(cetable)
devtools::load_all()
```


## Table of Contents
1. [Introduction](#intro)
2. [Error tables](#2)
3. [Coverage tables](#3)
  
## <a name="intro"></a>
## Introduction
cetable is a package for calculating errors and coverage. Output is formated to produce tables. Use cetable::exampledata as a guide to format your data before using cetable.

## <a name="2"></a>
## Error tables
```{r}
error_data(data = exampledata, 
           parameter = "pcst", 
           estimate = "50%", 
           totalerror_sd = "totalerror_sd",
           subset = "agegroup")  %>%
  kableExtra::kable() %>%
  kableExtra::column_spec(1:2, bold = T) %>%
  kableExtra::collapse_rows(columns = 1:2, valign = "top")
```

## <a name="3"></a>
## Coverage tables
If provided a subset column name, coverage will be calculate for each subset.
```{r}
coverage(data = exampledata, 
         parameter = "pcst", 
         lower = "2.5%", 
         upper = "97.5%", 
         subset = "agegroup")  %>%
  kableExtra::kable() %>%
  kableExtra::column_spec(1, bold = T)
```

```{r}
coverage(data = exampledata, 
         parameter = "pcst", 
         lower = "2.5%", 
         upper = "97.5%", 
         subset = "sourcename")  %>%
    kableExtra::kable()

# t <- coverage(exampledata, "pcst", "2.5%", "97.5%", subset = "sourcename")
```